export const SIDEBAR_OPENED = 'SIDEBAR_OPENED';
export const SIDEBAR_CLOSED = 'SIDEBAR_CLOSED';
export const SIDEBAR_TOGGLED = 'SIDEBAR_TOGGLED';

export const INJECT_ACCESS_TOKEN = 'INJECT_ACCESS_TOKEN';

