export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const CONNECT_SPOTIFY = 'CONNECT_SPOTIFY';
export const CONNECT_SPOTIFY_SUCCESS = 'CONNECT_SPOTIFY_SUCCESS';
export const CONNECT_SPOTIFY_FAILURE = 'CONNECT_SPOTIFY_FAILURE';